#ifndef APEP_VERSION_H
#define APEP_VERSION_H

#define APEP_ABI_VERSION_MAJOR 1u
#define APEP_ABI_VERSION_MINOR 0u
#define APEP_ABI_VERSION_PATCH 0u

#define APEP_ABI_VERSION_PACKED \
    ((APEP_ABI_VERSION_MAJOR << 16u) | (APEP_ABI_VERSION_MINOR << 8u) | (APEP_ABI_VERSION_PATCH))

#endif /* APEP_VERSION_H */
